trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "Reading test cases from JSON file..."
    cat test_cases.json
  displayName: 'Print Test Cases'
  continueOnError: false
